"""empty message

Revision ID: e3d4150b6eb3
Revises: f262031e18f3
Create Date: 2019-03-29 15:07:51.182000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e3d4150b6eb3'
down_revision = 'f262031e18f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cmdb_user', sa.Column('_password', sa.String(length=100), nullable=False))
    op.drop_column('cmdb_user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cmdb_user', sa.Column('password', mysql.VARCHAR(length=100), nullable=False))
    op.drop_column('cmdb_user', '_password')
    # ### end Alembic commands ###
